// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: updateUser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const putUser = `-- name: PutUser :one
UPDATE users
  SET email = $2,
      hashed_password =$3,
      updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, email, hashed_password
`

type PutUserParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) PutUser(ctx context.Context, arg PutUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, putUser, arg.ID, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
