// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: userExistsByID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const userExistsByID = `-- name: UserExistsByID :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE id = $1
)
`

func (q *Queries) UserExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistsByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
